language: python
install:
  - pip install tox
  - python3 setup.py egg_info
  - pip install -r aiosmtpd.egg-info/requires.txt
matrix:
  include:
    - python: "3.4"
      env: INTERP=py34 PYTHONASYNCIODEBUG=1
    - python: "3.5"
      env: INTERP=py35 PYTHONASYNCIODEBUG=1
    - python: "3.6"
      env: INTERP=py36 PYTHONASYNCIODEBUG=1
script:
  - tox -e $INTERP-nocov,$INTERP-cov,qa,docs
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then tox -e $INTERP-diffcov; fi'
