language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install tox
  - python3 setup.py egg_info
  - pip install -r aiosmtpd.egg-info/requires.txt
env: INTERP=py${TRAVIS_PYTHON_VERSION//./} PYTHONASYNCIODEBUG=1
before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8711
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
script: tox -e $INTERP-cov,qa,docs
before_script:
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
after_success:
  - bash <(curl -s https://codecov.io/bash)
