language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install tox
  - python3 setup.py egg_info
  - pip install -r aiosmtpd.egg-info/requires.txt
env:
  - PYTHONASYNCIODEBUG=1
script:
  - tox
